# Copyright Contributors to the Open Cluster Management project

name: Tests

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main, release-* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
      name: itdove/gitactions-test-dco     <-- clone https://github.com/org1/repo1
      ref: refs/heads/release
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${{ github.head_ref }})"
      id: extract_branch
    - name: DCO
      run: make dco BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}
